Repository MIT-Emerging-Talent/ET6-CDSP-group-23-repo, pull requests merged in 2025-07, with the labels that each got.

#38 data_preparation.exploration_for player_stats_Dataset
  1_datasets/player_stats_data.raw.csv
  1_datasets/player_stats_data_clean.csv
  1_datasets/transfer_dataset.cleaned.csv
  1_datasets/transfer_dataset.raw.csv
  2_data_preparation/README.md
  2_data_preparation/player_stats_data_preparation.ipynb
  2_data_preparation/transfer_dataset_data_preparation.ipynb
  3_data_exploration/README.md
  3_data_exploration/player_stats_data_exploration.ipynb
  3_data_exploration/transfer_dataset_data_exploration.ipynb
Labels: enhancement

#42 Meetings
  notes/meetings/README.md
  notes/meetings/milestone0_meetings.md
  notes/meetings/milestone1_meetings.md
  notes/meetings/milestone2_meetings.md
  notes/meetings/milestone3_meetings.md
  notes/meetings/milestone4_meetings.md
  notes/meetings/milestone5_meetings.md
Labels: documentation

#29 data scraping script modification
  1_datasets/fotmob_scraper.py
Labels: enhancement

#60 Add Random Forest Models to Predict Successful Transfers
  4_data_analysis/rf_models_summary.md
  4_data_analysis/rf_predicting_transfer_attackers.ipynb
  4_data_analysis/rf_predicting_transfer_defenders.ipynb
  4_data_analysis/rf_predicting_transfer_midfielders.ipynb
Labels: enhancement

#64 Deleted irrelevant datasets files
  1_datasets/2020-21_Transfers_2018-19_to_2021-22_Stats.raw.csv.csv
  1_datasets/2021-22_Transfers_2019-20_to_2022-23_Stats.raw.csv.csv
  3_data_exploration/player_stats_data_exploration.ipynb
Labels: enhancement

#68 Fix dataset path — use raw GitHub URL for portability
  4_data_analysis/rf_predicting_transfer_attackers.ipynb
  4_data_analysis/rf_predicting_transfer_defenders.ipynb
  4_data_analysis/rf_predicting_transfer_midfielders.ipynb
Labels: bug

#69 Player Stats Data Exploration
  3_data_exploration/Players_Stats_Dataset_Data_Exploration.ipynb
  3_data_exploration/README.md
Labels: documentation, enhancement

#61 Data refresh and cleaning
  .gitignore
  1_datasets/README.md
  1_datasets/cleaned/post_transfer.cleaned.csv
  1_datasets/cleaned/pre_transfer.cleaned.csv
  1_datasets/cleaned/transfer_dataset.cleaned.csv
  1_datasets/labeled/post_transfer_labeled_clean.csv
  1_datasets/labeled/post_transfer_labeled_raw.csv
  1_datasets/labeled/pre_transfer_labeled_clean.csv
  1_datasets/labeled/pre_transfer_labeled_raw.csv
  1_datasets/raw/2018-19_Transfers_2016-17_to_2019-20_Stats.raw.csv
  1_datasets/raw/2019-20_Transfers_2017-18_to_2020-21_Stats.raw.csv
  1_datasets/raw/2020-21_Transfers_2018-19_to_2021-22_Stats.raw.csv
  1_datasets/raw/2021-22_Transfers_2019-20_to_2022-23_Stats.raw.csv
  1_datasets/raw/2022-23_Transfers_2020-21_to_2023-24_Stats.raw.csv
  1_datasets/raw/transfer_dataset.raw.csv
  1_datasets/scaled_normalized/pre_transfer_labeled_scaled_clean.csv
  2_data_preparation/README.md
  2_data_preparation/player_stats_data_preparation.ipynb
  2_data_preparation/player_stats_data_preperation.ipynb
Labels: documentation, enhancement

#66 add the documentations
  .vscode/settings.json
  4_data_analysis/Confusion Matrix-Attackers.png
  4_data_analysis/Confusion Matrix-Defenders.png
  4_data_analysis/Confusion Matrix-Midfielders.png
  4_data_analysis/README.md
  4_data_analysis/non_technical_report.md
  4_data_analysis/technical_report.md
Labels: documentation

#72 Update labeling_data file
  4_data_analysis/labeling_data.ipynb
Labels: bug, documentation

#75 Fix broken read_csv URLs and add normalization.ipynb to data preparation
  2_data_preparation/normalization.ipynb
  4_data_analysis/labeling_data.ipynb
  4_data_analysis/rf_predicting_transfer_attackers.ipynb
  4_data_analysis/rf_predicting_transfer_defenders.ipynb
  4_data_analysis/rf_predicting_transfer_midfielders.ipynb
Labels: bug

#76 Milestone 3 Retrospective
  collaboration/retrospectives/3_data_analysis.md
  collaboration/retrospectives/README.md
Labels: documentation
